version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2.cli-migrations
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
  hasaura-cli:
    build: ./
    depends_on:
      - "graphql-engine"
    restart: always
    ports:
      - "9695:9695"
    volumes:
      - ./migrations:/hasura-migrations
volumes:
  db_data:
